files:
  - source: /docs/en/**/*.md
    translation: /docs/%two_letters_code%/**/%original_file_name%
    type: markdown
  - source: /resources/examples/*/readme.md
    translation: /resources/examples/*/readme.%two_letters_code%.md
    type: markdown
