files:
  - source: /docs/en/**/*.md
    translation: /docs/%two_letters_code%/**/%original_file_name%
  - source: /resources/examples/*/readme.md
    translation: /%original_path%/readme.%two_letters_code%.md
