files:
  - source: docs/en/**/*.md
    translation: docs/%two_letters_code%/**/%original_file_name%
    type: markdown
    languages_mapping:
      two_letters_code:
        zh-CN: zh
  - source: resources/examples/*/readme.md
    translation: /%original_path%/readme.%two_letters_code%.md
    type: markdown
    languages_mapping:
      two_letters_code:
        zh-CN: zh
